import type { Product } from './types';

/**
 * Демонстрационный каталог — локальная копия (Том 0, п. 0.3).
 * Ключи attributes совпадают с ключами фильтров категории (Том 3, п. 3.5),
 * чтобы товар корректно попадал в фильтрацию. В боевой версии эти данные
 * приезжают из PFS APP по API; здесь — сид для автономной работы витрины.
 */
export const products: Product[] = [
  // ─── Боксёрские мешки ───────────────────────────────────────────────
  {
    sku: 'MSH-120-40',
    slug: 'meshok-pfs-120',
    categorySlug: 'boksyorskie-meshki',
    subcategorySlug: 'cilindricheskie',
    name: 'Мешок боксёрский PFS-120',
    attributes: { weight: 40, height: 120, diameter: '35 см', material: 'ПВХ', filler: 'Резиновая крошка', mount: 'Цепи', purpose: 'Зал', availability: true },
    priceRetail: 78000,
    stockStatus: 'in_stock',
    productionDays: 5,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Вес', value: '40 кг' },
      { label: 'Высота', value: '120 см' },
      { label: 'Материал', value: 'ПВХ' },
    ],
    description:
      'Флагманский цилиндрический мешок для зала. Обшивка из армированного ПВХ, двойной шов по нагруженным зонам, наполнитель из резиновой крошки даёт плотный «жёсткий» отклик. Крепление на четырёх цепях с вертлюгом в комплекте.',
    forWhom: 'Подойдёт для взрослого бойца весом 70–90 кг, зал и регулярные тренировки.',
    relatedSkus: ['PCH-BX-14', 'AKS-CEP-4', 'MSH-150-55'],
    faq: [
      { q: 'Выдержит ли крепление удары апперкотом?', a: 'Да. Верхнее кольцо и цепи рассчитаны на ударную нагрузку свыше 200 кг, апперкоты держит без проблем.' },
      { q: 'Можно ли заказать другой вес?', a: 'Да, изготовим этот мешок в диапазоне 30–60 кг под ваш запрос. Срок — от 5 дней.' },
    ],
    updatedAt: '2026-07-20T10:00:00.000Z',
  },
  {
    sku: 'MSH-150-55',
    slug: 'meshok-pfs-150',
    categorySlug: 'boksyorskie-meshki',
    subcategorySlug: 'cilindricheskie',
    name: 'Мешок боксёрский PFS-150',
    attributes: { weight: 55, height: 150, diameter: '40 см', material: 'Натуральная кожа', filler: 'Комбинированный', mount: 'Цепи', purpose: 'Тайский бокс', availability: false },
    priceRetail: 135000,
    stockStatus: 'made_to_order',
    productionDays: 7,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Вес', value: '55 кг' },
      { label: 'Высота', value: '150 см' },
      { label: 'Материал', value: 'Натуральная кожа' },
    ],
    description:
      'Высокий тяжёлый мешок под тайский бокс и работу ногами. Обшивка из натуральной кожи, комбинированный наполнитель — плотный низ и более мягкий верх. Изготавливается под заказ.',
    forWhom: 'Для профессионалов и залов тайского бокса, боец 85–100 кг.',
    relatedSkus: ['PED-TAI-L', 'AKS-CEP-4'],
    faq: [
      { q: 'Почему кожа, а не ПВХ?', a: 'Натуральная кожа дольше держит форму при работе ногами и не дубеет на холоде. Для интенсивного тайского зала это оправдано.' },
    ],
    updatedAt: '2026-07-21T10:00:00.000Z',
  },
  {
    sku: 'MSH-APP-45',
    slug: 'meshok-apperkotnyj-pfs',
    categorySlug: 'boksyorskie-meshki',
    subcategorySlug: 'appperkotnye',
    name: 'Мешок апперкотный PFS-Upper',
    attributes: { weight: 45, height: 100, diameter: '40 см', material: 'ПВХ', filler: 'Резиновая крошка', mount: 'Цепи', purpose: 'Зал', availability: true },
    priceRetail: 92000,
    stockStatus: 'in_stock',
    productionDays: 6,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Вес', value: '45 кг' },
      { label: 'Форма', value: 'Апперкотная' },
      { label: 'Материал', value: 'ПВХ' },
    ],
    description:
      'Мешок расширенной формы для отработки апперкотов и работы в ближнем бою. Наклонная нижняя часть подставляется под удар снизу.',
    forWhom: 'Для боксёрских залов, отработка ударов снизу и в корпус.',
    relatedSkus: ['PCH-BX-14'],
    updatedAt: '2026-07-19T10:00:00.000Z',
  },
  {
    sku: 'MSH-RAST-25',
    slug: 'meshok-na-rastyazhkah',
    categorySlug: 'boksyorskie-meshki',
    subcategorySlug: 'na-rastyazhkah',
    name: 'Мешок на растяжках PFS-Home',
    attributes: { weight: 25, height: 100, diameter: '30 см', material: 'Тент', filler: 'Текстиль', mount: 'Растяжки', purpose: 'Дом', availability: true },
    priceRetail: 46000,
    stockStatus: 'in_stock',
    productionDays: 5,
    salesChannel: 'both',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Вес', value: '25 кг' },
      { label: 'Крепление', value: 'Растяжки' },
      { label: 'Материал', value: 'Тент' },
    ],
    description:
      'Мешок с креплением на верхних и нижних растяжках — не требует потолочного крюка. Решение для квартир с гипсокартоном или натяжным потолком.',
    forWhom: 'Для дома, где нельзя сверлить бетонное перекрытие. Взрослый и подросток.',
    relatedSkus: ['AKS-CEP-4', 'PCH-SN-12'],
    faq: [
      { q: 'Можно ли повесить на гипсокартон?', a: 'Да, это как раз решение для гипсокартона: растяжки распределяют нагрузку между полом и потолком/стеной, точечной нагрузки на лист нет.' },
    ],
    updatedAt: '2026-07-18T10:00:00.000Z',
  },
  {
    sku: 'MSH-DET-15',
    slug: 'meshok-detskij-pfs',
    categorySlug: 'boksyorskie-meshki',
    subcategorySlug: 'detskie',
    name: 'Мешок детский PFS-Kids',
    attributes: { weight: 15, height: 80, diameter: '25 см', material: 'Тент', filler: 'Текстиль', mount: 'Цепи', purpose: 'Дети', availability: true },
    priceRetail: 32000,
    stockStatus: 'in_stock',
    productionDays: 5,
    salesChannel: 'both',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Вес', value: '15 кг' },
      { label: 'Высота', value: '80 см' },
      { label: 'Для', value: 'Детей' },
    ],
    description: 'Лёгкий мягкий мешок для детей до 12 лет. Мягкий текстильный наполнитель, безопасная обшивка из тента.',
    forWhom: 'Для детей до 12 лет, первые тренировки дома или в детской секции.',
    updatedAt: '2026-07-17T10:00:00.000Z',
  },
  {
    sku: 'MSH-VOD-30',
    slug: 'grusha-vodonalivnaya-napolnaya',
    categorySlug: 'boksyorskie-meshki',
    subcategorySlug: 'vodonalivnye',
    name: 'Груша водоналивная напольная PFS-Aqua',
    attributes: { weight: 30, height: 160, diameter: '35 см', material: 'ПВХ', filler: 'Комбинированный', mount: 'Напольный', purpose: 'Дом', availability: false },
    priceRetail: null,
    priceFrom: false,
    stockStatus: 'on_request',
    productionDays: 7,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Тип', value: 'Напольная' },
      { label: 'Высота', value: '160 см' },
      { label: 'Крепление', value: 'Не нужно' },
    ],
    description: 'Напольная груша на водоналивном основании — не требует крепления вовсе. Вес регулируется объёмом воды.',
    forWhom: 'Для дома и офиса, где нельзя ничего крепить к стенам и потолку.',
    updatedAt: '2026-07-16T10:00:00.000Z',
  },

  // ─── Манекены ───────────────────────────────────────────────────────
  {
    sku: 'MAN-BOR-160',
    slug: 'maneken-borcovskij-160',
    categorySlug: 'manekeny',
    subcategorySlug: 'borcovskie',
    name: 'Манекен борцовский PFS-160',
    attributes: { height: 160, weight: 35, discipline: 'Борьба', material: 'ПВХ', filler: 'Текстиль' },
    priceRetail: 148000,
    stockStatus: 'made_to_order',
    productionDays: 8,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Рост', value: '160 см' },
      { label: 'Вес', value: '35 кг' },
      { label: 'Дисциплина', value: 'Борьба' },
    ],
    description: 'Классический борцовский манекен с руками для отработки бросков и захватов. Плотная набивка, армированные швы в зонах захвата.',
    forWhom: 'Для борцовских залов, имитация соперника ростом ~160 см.',
    relatedSkus: ['MAN-MMA-170'],
    updatedAt: '2026-07-15T10:00:00.000Z',
  },
  {
    sku: 'MAN-MMA-170',
    slug: 'maneken-mma-170',
    categorySlug: 'manekeny',
    subcategorySlug: 'mma',
    name: 'Манекен для ММА PFS-170',
    attributes: { height: 170, weight: 45, discipline: 'ММА / грэпплинг', material: 'Натуральная кожа', filler: 'Комбинированный' },
    priceRetail: 195000,
    stockStatus: 'made_to_order',
    productionDays: 10,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Рост', value: '170 см' },
      { label: 'Вес', value: '45 кг' },
      { label: 'Дисциплина', value: 'ММА' },
    ],
    description: 'Манекен для грэпплинга и ММА с проработанными конечностями для партера. Кожаная обшивка выдерживает интенсивную работу на полу.',
    forWhom: 'Для ММА-залов, имитация соперника ~170 см / 70–80 кг.',
    updatedAt: '2026-07-14T10:00:00.000Z',
  },
  {
    sku: 'MAN-DET-120',
    slug: 'maneken-detskij-120',
    categorySlug: 'manekeny',
    subcategorySlug: 'detskie',
    name: 'Манекен детский PFS-120',
    attributes: { height: 120, weight: 18, discipline: 'Борьба', material: 'ПВХ', filler: 'Текстиль' },
    priceRetail: 74000,
    stockStatus: 'in_stock',
    productionDays: 7,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Рост', value: '120 см' },
      { label: 'Вес', value: '18 кг' },
      { label: 'Для', value: 'Детей' },
    ],
    description: 'Облегчённый манекен для детских секций борьбы. Меньший рост и вес под юного спортсмена.',
    forWhom: 'Детские секции борьбы, спортсмены до 14 лет.',
    updatedAt: '2026-07-13T10:00:00.000Z',
  },

  // ─── Утяжелители ────────────────────────────────────────────────────
  {
    sku: 'UTZ-ZHL-10',
    slug: 'zhilet-utyazhelitel-10',
    categorySlug: 'utyazheliteli',
    subcategorySlug: 'zhilety',
    name: 'Жилет-утяжелитель PFS 10 кг',
    attributes: { weight: 10, adjustable: true, fixation: 'Липучка', size: 'Универсальный' },
    priceRetail: 24000,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Вес', value: '10 кг' },
      { label: 'Регулировка', value: 'Есть' },
      { label: 'Размер', value: 'Универсал' },
    ],
    description: 'Жилет-утяжелитель с регулируемым весом сменными пластинами. Плотная фиксация на липучках и ремнях.',
    forWhom: 'ОФП, кроссфит, функциональный тренинг.',
    updatedAt: '2026-07-12T10:00:00.000Z',
  },
  {
    sku: 'UTZ-MAN-2',
    slug: 'manzhety-nogi-2',
    categorySlug: 'utyazheliteli',
    subcategorySlug: 'manzhety-nogi',
    name: 'Манжеты на ноги PFS 2×2 кг',
    attributes: { weight: 4, adjustable: false, fixation: 'Липучка', size: 'Универсальный' },
    priceRetail: 9000,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Вес пары', value: '4 кг' },
      { label: 'Фиксация', value: 'Липучка' },
    ],
    description: 'Пара манжет по 2 кг на голени. Мягкая подкладка, широкая липучка не сползает при беге.',
    forWhom: 'Беговые и ударные тренировки, реабилитация.',
    updatedAt: '2026-07-11T10:00:00.000Z',
  },

  // ─── Лапы и пэды ────────────────────────────────────────────────────
  {
    sku: 'PED-TAI-L',
    slug: 'tajskie-pedy-pfs',
    categorySlug: 'lapy-i-pedy',
    subcategorySlug: 'tajskie-pedy',
    name: 'Тайские пэды PFS Pro (пара)',
    attributes: { discipline: 'Тайский бокс', material: 'Натуральная кожа', size: 'L', shock: true },
    priceRetail: 42000,
    stockStatus: 'in_stock',
    productionDays: 6,
    salesChannel: 'both',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Дисциплина', value: 'Тайский бокс' },
      { label: 'Материал', value: 'Нат. кожа' },
      { label: 'Амортизация', value: 'Есть' },
    ],
    description: 'Пара тайских пэдов из натуральной кожи с усиленной амортизацией. Держат мощные лоу-кики и удары коленями, берегут руки тренера.',
    forWhom: 'Тренеры тайского бокса и ММА, интенсивная работа на лапах.',
    relatedSkus: ['MSH-150-55'],
    updatedAt: '2026-07-10T10:00:00.000Z',
  },
  {
    sku: 'PED-BX-M',
    slug: 'boksyorskie-lapy-pfs',
    categorySlug: 'lapy-i-pedy',
    subcategorySlug: 'boksyorskie-lapy',
    name: 'Боксёрские лапы PFS (пара)',
    attributes: { discipline: 'Бокс', material: 'Кожзам', size: 'M', shock: true },
    priceRetail: 21000,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Дисциплина', value: 'Бокс' },
      { label: 'Размер', value: 'M' },
    ],
    description: 'Лёгкие боксёрские лапы для отработки прямых и боковых. Изогнутая ударная поверхность, вентилируемая ладонь.',
    forWhom: 'Боксёрские секции, работа на скорость и точность.',
    updatedAt: '2026-07-09T10:00:00.000Z',
  },

  // ─── Настенные подушки ──────────────────────────────────────────────
  {
    sku: 'NP-STD-120',
    slug: 'nastennaya-podushka-120',
    categorySlug: 'nastennye-podushki',
    name: 'Настенная подушка PFS 120×60',
    attributes: { width: 120, height: 60, thickness: '10 см', material: 'ПВХ', mount: 'Люверсы' },
    priceRetail: 38000,
    priceFrom: true,
    stockStatus: 'made_to_order',
    productionDays: 6,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Размер', value: '120×60 см' },
      { label: 'Толщина', value: '10 см' },
      { label: 'Крепление', value: 'Люверсы' },
    ],
    description: 'Настенная ударная подушка для отработки ударов у стены. Базовый размер 120×60; изготовим точно под вашу стену.',
    forWhom: 'Залы и домашние спортуголки с ограниченным местом.',
    relatedSkus: ['AKS-CEP-4'],
    faq: [
      { q: 'Сделаете нестандартный размер?', a: 'Да, это профильная категория под заказ — назовите ширину и высоту, рассчитаем стоимость.' },
    ],
    updatedAt: '2026-07-08T10:00:00.000Z',
  },

  // ─── Покрытия и маты ────────────────────────────────────────────────
  {
    sku: 'POK-TAT-40',
    slug: 'tatami-pfs-40mm',
    categorySlug: 'pokrytiya-i-maty',
    subcategorySlug: 'tatami',
    name: 'Татами PFS 40 мм (за м²)',
    attributes: { thickness: '40 мм', density: 'Высокая', purpose: 'Борьба', color: 'Красный', surface: 'Тиснёная' },
    priceRetail: 14000,
    priceFrom: true,
    stockStatus: 'made_to_order',
    productionDays: 10,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Толщина', value: '40 мм' },
      { label: 'Плотность', value: 'Высокая' },
      { label: 'Цена', value: 'за м²' },
    ],
    description: 'Татами 40 мм высокой плотности с тиснёной противоскользящей поверхностью «рисовая соломка». Цена указана за квадратный метр; рассчитаем на площадь зала.',
    forWhom: 'Залы борьбы, дзюдо, тхэквондо. Стыкуется по системе «ласточкин хвост».',
    relatedSkus: ['POK-MAT-25'],
    faq: [
      { q: 'Как рассчитать площадь?', a: 'Умножьте длину на ширину зоны укладки и добавьте 5% на подрезку. Пришлите размеры — посчитаем и дадим смету.' },
    ],
    updatedAt: '2026-07-07T10:00:00.000Z',
  },
  {
    sku: 'POK-MAT-25',
    slug: 'mat-gimnasticheskij-25',
    categorySlug: 'pokrytiya-i-maty',
    subcategorySlug: 'maty',
    name: 'Мат гимнастический PFS 25 мм',
    attributes: { thickness: '25 мм', density: 'Средняя', purpose: 'Универсал', color: 'Синий', surface: 'Гладкая' },
    priceRetail: 11000,
    priceFrom: true,
    stockStatus: 'in_stock',
    productionDays: 7,
    salesChannel: 'request',
    made: true,
    keyParams: [
      { label: 'Толщина', value: '25 мм' },
      { label: 'Назначение', value: 'Универсал' },
    ],
    description: 'Складной гимнастический мат средней плотности. Съёмный чехол из ПВХ, ручки для переноски.',
    forWhom: 'Секции, школы, домашние тренировки.',
    updatedAt: '2026-07-06T10:00:00.000Z',
  },

  // ─── Перчатки и защита ──────────────────────────────────────────────
  {
    sku: 'PCH-BX-14',
    slug: 'perchatki-boksyorskie-14oz',
    categorySlug: 'perchatki-i-zashchita',
    subcategorySlug: 'boksyorskie',
    name: 'Перчатки боксёрские PFS 14 oz',
    attributes: { oz: '14 oz', size: 'L', material: 'Натуральная кожа', discipline: 'Бокс', age: 'Взрослые' },
    priceRetail: 28000,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Унции', value: '14 oz' },
      { label: 'Материал', value: 'Нат. кожа' },
    ],
    description: 'Боксёрские перчатки 14 oz из натуральной кожи для спарринга и работы на мешке. Многослойный формованный наполнитель, широкая липучка-манжет.',
    forWhom: 'Боец 60–75 кг для спарринга; для снарядной работы возьмите 12 oz.',
    relatedSkus: ['PCH-SN-12', 'ZSH-KAP'],
    updatedAt: '2026-07-05T10:00:00.000Z',
  },
  {
    sku: 'PCH-SN-12',
    slug: 'perchatki-snaryadnye-12oz',
    categorySlug: 'perchatki-i-zashchita',
    subcategorySlug: 'snaryadnye',
    name: 'Перчатки снарядные PFS 12 oz',
    attributes: { oz: '12 oz', size: 'M', material: 'Кожзам', discipline: 'Бокс', age: 'Взрослые' },
    priceRetail: 16000,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Унции', value: '12 oz' },
      { label: 'Тип', value: 'Снарядные' },
    ],
    description: 'Снарядные перчатки 12 oz для работы на мешке и лапах. Плотный наполнитель бережёт кисть при частых ударах.',
    forWhom: 'Работа на мешке и лапах, боец 60–80 кг.',
    updatedAt: '2026-07-04T10:00:00.000Z',
  },
  {
    sku: 'ZSH-KAP',
    slug: 'kapa-boksyorskaya',
    categorySlug: 'perchatki-i-zashchita',
    subcategorySlug: 'kapy',
    name: 'Капа боксёрская PFS',
    attributes: { size: 'M', material: 'ПВХ', discipline: 'Бокс', age: 'Взрослые' },
    priceRetail: 3500,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: false,
    keyParams: [
      { label: 'Тип', value: 'Одночелюстная' },
    ],
    description: 'Термоформируемая капа с футляром. Подгоняется под прикус в горячей воде.',
    forWhom: 'Спарринги во всех ударных дисциплинах.',
    updatedAt: '2026-07-03T10:00:00.000Z',
  },

  // ─── Аксессуары ─────────────────────────────────────────────────────
  {
    sku: 'AKS-CEP-4',
    slug: 'podves-cepnoj-4-tochki',
    categorySlug: 'aksessuary',
    name: 'Подвес цепной 4-точечный с вертлюгом',
    attributes: { type: 'Крепёж' },
    priceRetail: 6500,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: false,
    keyParams: [
      { label: 'Тип', value: 'Крепёж' },
      { label: 'Точек', value: '4 + вертлюг' },
    ],
    description: 'Четырёхточечный цепной подвес с вращающимся вертлюгом. Подходит к большинству цилиндрических мешков.',
    forWhom: 'Замена крепления или дозаказ к мешку.',
    updatedAt: '2026-07-02T10:00:00.000Z',
  },
  {
    sku: 'AKS-CHL-M',
    slug: 'chehol-dlya-meshka',
    categorySlug: 'aksessuary',
    name: 'Чехол для перевозки мешка',
    attributes: { type: 'Чехлы' },
    priceRetail: 7500,
    stockStatus: 'in_stock',
    salesChannel: 'kaspi',
    kaspiUrl: 'https://kaspi.kz/shop/',
    made: true,
    keyParams: [
      { label: 'Тип', value: 'Чехол' },
    ],
    description: 'Плотный чехол из ПВХ для хранения и перевозки боксёрского мешка. Ручки и молния по всей длине.',
    forWhom: 'Клубы, выездные тренировки.',
    updatedAt: '2026-07-01T10:00:00.000Z',
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function productsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function productBySku(sku: string): Product | undefined {
  return products.find((p) => p.sku === sku);
}
